In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import datasets

In [3]:
digits = datasets.load_digits()
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [5]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
digits.data.shape

(1797, 64)

In [9]:
digits.target.shape

(1797,)

In [11]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [12]:
X = digits.data
y = digits.target

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

In [16]:
X_train

array([[ 0.,  0., 11., ...,  2.,  0.,  0.],
       [ 0.,  0.,  2., ...,  1.,  0.,  0.],
       [ 0.,  1., 15., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  3.,  0.,  0.],
       [ 0.,  0.,  4., ...,  0.,  0.,  0.],
       [ 0.,  0.,  3., ..., 16., 16.,  3.]])

In [55]:
knn = KNeighborsClassifier(n_neighbors=13)

In [56]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [57]:
round(knn.score(X_train, y_train), 4)

0.9833

In [20]:
neighbors = np.arange(1, 9)
train_accuracy = np.empty(len(neighbors))
test_accuracy = np.empty(len(neighbors))

In [24]:
train_accuracy

array([0.14023372, 0.14190317, 0.33889816, 0.34056761, 0.53923205,
       0.5409015 , 0.73956594, 0.93989983])

In [25]:
for i, k in enumerate(neighbors):
        # Cree un clasificador con k vecinos
        knn = KNeighborsClassifier(n_neighbors=k)

        # Entrene el clasificador con los datos de entrenamiento
        knn.fit(X_train,y_train)

        # Calcule la precisión para el conjunto de datos de entrenamiento
        train_accuracy[i] = knn.score(X_train, y_train)

        # Calcule la precisión para el conjunto de datos de prueba
        test_accuracy[i] = knn.score(X_test, y_test)


In [26]:
df = pd.DataFrame(
        {
            "k": neighbors,
            "train_accuracy": train_accuracy,
            "test_accuracy": test_accuracy,
        }
    )

In [27]:
df

k  train_accuracy  test_accuracy
0  1        1.000000       0.986111
1  2        0.991649       0.986111
2  3        0.993737       0.986111
3  4        0.993737       0.983333
4  5        0.991649       0.983333
5  6        0.989562       0.980556
6  7        0.990257       0.983333
7  8        0.989562       0.977778